import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function geocode(strasse: string, plz: string, ort: string) {
  const q = encodeURIComponent(`${strasse}, ${plz} ${ort}, Schweiz`)
  const url = `https://nominatim.openstreetmap.org/search?q=${q}&format=json&limit=1&countrycodes=ch`
  try {
    const res = await fetch(url, { headers: { 'User-Agent': 'FreeImmo/1.0 (freeimmo.ch)' } })
    if (!res.ok) return null
    const data = await res.json()
    if (!data.length) return null
    return { lat: parseFloat(data[0].lat), lng: parseFloat(data[0].lon) }
  } catch {
    return null
  }
}

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms))

async function main() {
  const demo = await prisma.user.upsert({
    where: { email: 'demo@freeimmo.ch' },
    update: {},
    create: { email: 'demo@freeimmo.ch', name: 'FreeImmo Demo' },
  })

  await prisma.inserat.deleteMany({ where: { userId: demo.id } })

  const inserate = [
    {
      titel: 'Helle 3.5-Zimmer-Wohnung an zentraler Lage',
      beschreibung: 'Wunderschöne, helle Wohnung im Herzen von Zürich. Die frisch renovierte Wohnung überzeugt mit moderner Küche, grossem Wohnzimmer und einem gemütlichen Balkon mit Aussicht. Öffentliche Verkehrsmittel direkt vor der Haustür.\n\nAusstattung:\n- Einbauküche mit Geschirrspüler\n- Parkettboden\n- Badezimmer mit Badewanne und Dusche\n- Kellerabteil inklusive\n- Waschküche im Haus',
      preis: 2450,
      zimmer: 3.5,
      flaeche: 82,
      strasse: 'Langstrasse 48',
      plz: '8004',
      ort: 'Zürich',
      kanton: 'ZH',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80'],
    },
    {
      titel: 'Modernes Studio – ideal für Singles und Pendler',
      beschreibung: 'Kompaktes, modern eingerichtetes Studio in ruhiger Quartierslage. Perfekt für Berufseinsteiger oder als Zweitwohnung. Vollständig renoviert, mit hochwertigen Materialien ausgestattet.\n\nDetails:\n- Offene Küche mit Induktionskochfeld\n- Duschbad\n- Einbauschrank\n- Nähe Bahnhof (5 Minuten zu Fuss)',
      preis: 1190,
      zimmer: 1,
      flaeche: 32,
      strasse: 'Bundesgasse 12',
      plz: '3011',
      ort: 'Bern',
      kanton: 'BE',
      typ: 'studio',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80'],
    },
    {
      titel: 'Grosszügiges Einfamilienhaus mit Garten',
      beschreibung: 'Traumhaftes Einfamilienhaus in ruhiger Wohngegend mit gepflegtem Garten und Doppelgarage. Das Haus wurde 2019 vollständig renoviert und bietet auf drei Etagen viel Platz für die ganze Familie.\n\nHighlights:\n- 5 Schlafzimmer\n- 2 Badezimmer (1× mit Badewanne)\n- Offene Wohnküche\n- Garten ca. 400 m²\n- Doppelgarage + 2 Aussenparkplätze\n- Keller mit Hobbyraum',
      preis: 1250000,
      zimmer: 6.5,
      flaeche: 210,
      strasse: 'Rosenweg 7',
      plz: '4132',
      ort: 'Muttenz',
      kanton: 'BL',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80'],
    },
    {
      titel: '4.5-Zimmer-Wohnung mit Seesicht',
      beschreibung: 'Exklusive Attikawohnung mit atemberaubender Seesicht auf den Vierwaldstättersee. Grosszügige Raumaufteilung, hochwertige Ausstattung und eine Dachterrasse von 45 m² machen diese Wohnung zu einem einzigartigen Angebot.\n\nAusstattung:\n- Dachterrasse 45 m² mit Seeblick\n- Designer-Küche\n- Eichenparkettboden\n- Tiefgaragenplatz inklusive\n- Concierge-Service',
      preis: 3800,
      zimmer: 4.5,
      flaeche: 140,
      strasse: 'Seepromenade 22',
      plz: '6006',
      ort: 'Luzern',
      kanton: 'LU',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
    },
    {
      titel: 'Renoviertes Reiheneinfamilienhaus',
      beschreibung: 'Charmantes Reiheneinfamilienhaus im Grünen, vollständig renoviert und bezugsbereit. Ruhige Lage mit direktem Zugang zu Wanderwegen. Sehr gute Schulen in der Nähe.\n\nDetails:\n- 4 Zimmer über 2 Etagen\n- Neues Bad (2023)\n- Neue Küche (2023)\n- Südausgerichteter Garten 120 m²\n- Carport für 1 Fahrzeug',
      preis: 890000,
      zimmer: 4.5,
      flaeche: 118,
      strasse: 'Im Gässli 3',
      plz: '8620',
      ort: 'Wetzikon',
      kanton: 'ZH',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80'],
    },
    {
      titel: '2-Zimmer-Wohnung – ruhig und sonnig',
      beschreibung: 'Helle 2-Zimmer-Wohnung in gepflegtem Mehrfamilienhaus. Südlage sorgt für viel Tageslicht. Ideal für ein Paar oder als Singlewohnung. Gute Anbindung ans ÖV-Netz.\n\nDetails:\n- Grosses Schlafzimmer\n- Wohnzimmer mit Balkon\n- Küche mit Essplatz\n- Abstellraum\n- Keller inklusive',
      preis: 1620,
      zimmer: 2,
      flaeche: 58,
      strasse: 'Schützenmattstrasse 61',
      plz: '4051',
      ort: 'Basel',
      kanton: 'BS',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80'],
    },
    {
      titel: 'Gewerbelokal im Zentrum – ideal für Büro oder Praxis',
      beschreibung: 'Helles Gewerbelokal an frequentierter Lage in der Zürcher Innenstadt. Repräsentative Eingangssituation, barrierefreier Zugang und gute Parkmöglichkeiten in der Nähe.\n\nEigenschaften:\n- Offener Grundriss, flexibel unterteilbar\n- WC-Anlage vorhanden\n- Glasfasernetz im Haus\n- Schaufensterfronten möglich',
      preis: 3200,
      zimmer: 3,
      flaeche: 95,
      strasse: 'Bahnhofstrasse 101',
      plz: '8001',
      ort: 'Zürich',
      kanton: 'ZH',
      typ: 'gewerbe',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80'],
    },
    {
      titel: 'Stadtnahe 5-Zimmer-Eigentumswohnung',
      beschreibung: 'Grosszügige Eigentumswohnung in gepflegtem Neubau von 2021. Ruhige Lage mit kurzer Distanz zum Bahnhof. Ideal für Familien mit Schulkindern.\n\nAusstattung:\n- 5 Zimmer inkl. 2 Kinderzimmer\n- Offene Wohnküche mit Kücheninsel\n- 2 Badezimmer\n- Terrasse 18 m²\n- Tiefgaragenplatz inklusive\n- Minergie-Standard',
      preis: 1450000,
      zimmer: 5,
      flaeche: 148,
      strasse: 'Neugutstrasse 15',
      plz: '8304',
      ort: 'Wallisellen',
      kanton: 'ZH',
      typ: 'wohnung',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&q=80'],
    },
    {
      titel: 'Charmante 2.5-Zimmer-Wohnung in der Altstadt',
      beschreibung: 'Stilvolle Altbau-Wohnung mit Originalparkett und hohen Stuckaturen in der Genfer Altstadt. Verkehrsberuhigte Lage, Einkaufsmöglichkeiten und Restaurants zu Fuss erreichbar.\n\nDetails:\n- Wohnzimmer mit Erker\n- Renovierte Küche mit Granit-Arbeitsplatte\n- Badezimmer mit Regendusche\n- Keller inklusive\n- ÖV-Anbindung hervorragend',
      preis: 2200,
      zimmer: 2.5,
      flaeche: 65,
      strasse: 'Rue de Rive 18',
      plz: '1204',
      ort: 'Genf',
      kanton: 'GE',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
    },
    {
      titel: 'Modernes Loft in umgebautem Industriegebäude',
      beschreibung: 'Einzigartiges Loft in einem stilvoll umgebauten Industriegebäude. Offene Raumkonzeption, Betondecken und grosse Stahlfenster sorgen für urbanes Flair. Perfekt für Kreative und Design-Liebhaber.\n\nHighlights:\n- Deckenhöhe 4.2 m\n- Offene Küche mit Kücheninsel\n- Galerie als zweite Schlafebene\n- Beizugbares Mezzanin\n- Fahrradkeller im Haus',
      preis: 2850,
      zimmer: 2.5,
      flaeche: 95,
      strasse: 'Hardturmstrasse 66',
      plz: '8005',
      ort: 'Zürich',
      kanton: 'ZH',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80'],
    },
    {
      titel: 'Freistehendes Einfamilienhaus mit Pool',
      beschreibung: 'Exklusives Einfamilienhaus in begehrter Wohnlage mit privatem Swimmingpool und grosszügigem Umschwung. Modernisiert 2022, hochwertige Innenausstattung durchgehend.\n\nAusstattung:\n- 6 Zimmer auf zwei Etagen\n- Pool 8×4 m mit Abdeckung\n- Garten ca. 600 m²\n- Doppelgarage\n- Sauna\n- Smart-Home-System',
      preis: 2850000,
      zimmer: 6.5,
      flaeche: 260,
      strasse: 'Obstgartenweg 4',
      plz: '8700',
      ort: 'Küsnacht',
      kanton: 'ZH',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=800&q=80'],
    },
    {
      titel: 'Gepflegte 3-Zimmer-Wohnung mit Parkplatz',
      beschreibung: 'Helle Familienwohnung im Hochparterre eines gepflegten Mehrfamilienhauses. Ruhige Wohnlage, Einkauf und Schule in wenigen Gehminuten erreichbar.\n\nDetails:\n- Wohnzimmer mit Balkon (Süd)\n- Elternschlafzimmer\n- Kinderzimmer\n- Küche mit Geschirrspüler\n- Parkplatz inklusive\n- Keller inklusive',
      preis: 1850,
      zimmer: 3,
      flaeche: 72,
      strasse: 'Breitenrainstrasse 44',
      plz: '3014',
      ort: 'Bern',
      kanton: 'BE',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80'],
    },
    {
      titel: 'Gemütliches Ferienhaus in den Bergen',
      beschreibung: 'Traditionelles Schweizer Chalet in sonniger Berglage, ideal als Feriendomizil oder Erstwohnsitz. Panoramablick auf Eiger, Mönch und Jungfrau. Ski-in/Ski-out Anbindung.\n\nHighlights:\n- 4 Schlafzimmer\n- Offener Cheminée im Wohnzimmer\n- Grosse Sonnenterrasse\n- Skiraum\n- Garage\n- Vermietet als Ferienwohnung (Erträge vorhanden)',
      preis: 1650000,
      zimmer: 5,
      flaeche: 150,
      strasse: 'Grindelwaldstrasse 22',
      plz: '3818',
      ort: 'Grindelwald',
      kanton: 'BE',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80'],
    },
    {
      titel: 'Bürofläche in modernem Businesscenter',
      beschreibung: 'Repräsentative Bürofläche im modernen Businesscenter Winterthur, direkt beim Hauptbahnhof. Vollausgestattete Infrastruktur, Empfangsdienst und Cafeteria im Haus.\n\nEigenschaften:\n- Grossraum- oder Zellenstruktur möglich\n- Klimaanlage\n- Doppelboden für Verkabelung\n- Tiefgaragenplätze zumietbar\n- Serverraum verfügbar',
      preis: 4800,
      zimmer: 4,
      flaeche: 120,
      strasse: 'Zürcherstrasse 310',
      plz: '8400',
      ort: 'Winterthur',
      kanton: 'ZH',
      typ: 'gewerbe',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80'],
    },
    {
      titel: 'Renovationsbedürftiges Einfamilienhaus mit viel Potenzial',
      beschreibung: 'Solides Einfamilienhaus aus den 1970er-Jahren in ruhiger Quartierslage. Ideales Projekt für Käufer, die nach ihren eigenen Vorstellungen gestalten möchten. Grosse Parzelle mit viel Grünfläche.\n\nDetails:\n- 5 Zimmer\n- Garten ca. 500 m²\n- Einfachgarage\n- Keller mit Hobbyraum\n- Zentrumsnahe Lage\n- Ausbau-/Anbaupotenzial vorhanden',
      preis: 720000,
      zimmer: 5,
      flaeche: 130,
      strasse: 'Rebbergstrasse 9',
      plz: '5400',
      ort: 'Baden',
      kanton: 'AG',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'],
    },
    {
      titel: '1.5-Zimmer-Studio – günstig und zentral',
      beschreibung: 'Kompaktes, gut geschnittenes Studio in zentraler Stadtlage. Frisch gestrichen und geputzt, bezugsbereit. Ideal für Studierende oder als günstige Singlewohnung.\n\nDetails:\n- Kochnische mit E-Herd\n- Duschbad\n- Grosses Fenster mit Stadtblick\n- Gemeinschaftswaschküche\n- ÖV direkt vor der Haustür',
      preis: 890,
      zimmer: 1.5,
      flaeche: 28,
      strasse: 'Markgässlein 5',
      plz: '4051',
      ort: 'Basel',
      kanton: 'BS',
      typ: 'studio',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80'],
    },
    {
      titel: 'Luxuriöse Penthouse-Wohnung mit Seesicht',
      beschreibung: 'Exklusives Penthouse mit atemberaubendem Blick auf den Zürichsee. Hochwertigste Ausstattung, private Dachterrasse und Concierge-Service rund um die Uhr. Einzigartiges Wohnflair auf höchstem Niveau.\n\nAusstattung:\n- Dachterrasse 80 m² mit Jacuzzi\n- Chef-Küche mit Gaggenau-Geräten\n- Master Suite mit Ankleide und Badezimmer en suite\n- 2 weitere Schlafzimmer\n- 2 Tiefgaragenplätze\n- Weinkeller',
      preis: 9800,
      zimmer: 4.5,
      flaeche: 220,
      strasse: 'Bellerivestrasse 99',
      plz: '8008',
      ort: 'Zürich',
      kanton: 'ZH',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80'],
    },
    {
      titel: 'Ladenlokal an Top-Passantenlage',
      beschreibung: 'Frequentiertes Ladenlokal an der Haupteinkaufsmeile St. Gallens. Grosse Schaufensterfront, ebenerdig und barrierefrei zugänglich. Lager und WC im Untergeschoss.\n\nDetails:\n- Verkaufsfläche 75 m²\n- Lagerfläche 30 m²\n- Schaufensterfront 8 m\n- Lieferanteneingang rückseitig\n- Starkstromanschluss vorhanden\n- Sofort verfügbar',
      preis: 3600,
      zimmer: 2,
      flaeche: 75,
      strasse: 'Marktgasse 14',
      plz: '9000',
      ort: 'St. Gallen',
      kanton: 'SG',
      typ: 'gewerbe',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&q=80'],
    },
    {
      titel: 'Neubauwohnung mit Tessiner Flair',
      beschreibung: 'Moderne 3.5-Zimmer-Wohnung in ruhiger Hanglage mit Blick auf den Lago di Lugano. Südausrichtung, grosser Balkon und mediterranes Ambiente. Neubau 2024, erstbezug.\n\nAusstattung:\n- Offene Küche mit Kücheninsel\n- Parkett im Wohnbereich\n- 2 Badezimmer\n- Balkon 20 m²\n- Tiefgaragenplatz\n- Gemeinschaftspool',
      preis: 2650,
      zimmer: 3.5,
      flaeche: 90,
      strasse: 'Via Nassa 12',
      plz: '6900',
      ort: 'Lugano',
      kanton: 'TI',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80'],
    },
    {
      titel: 'Doppeleinfamilienhaus – eine Hälfte zu verkaufen',
      beschreibung: 'Gepflegte Doppelhaushälfte in familienfreundlichem Quartier. Gut unterhaltener Zustand, einziehbereit. Direkter Gartenzugang und ruhige Nachbarschaft.\n\nDetails:\n- 4.5 Zimmer auf 2 Etagen\n- Küche mit Granitabdeckung\n- Badezimmer + Gäste-WC\n- Garten 180 m²\n- Carport\n- Keller',
      preis: 980000,
      zimmer: 4.5,
      flaeche: 125,
      strasse: 'Lindenstrasse 34a',
      plz: '3600',
      ort: 'Thun',
      kanton: 'BE',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1575517111839-3a3843ee7f5d?w=800&q=80'],
    },
    {
      titel: 'Helle 4-Zimmer-Wohnung nahe der Aare',
      beschreibung: 'Geräumige Familienwohnung in direkter Areanähe. Grosser Balkon mit Blick ins Grüne, moderne Küche und zwei grosszügige Schlafzimmer. Kindergarten und Primarschule fussläufig.\n\nDetails:\n- Wohnzimmer 35 m²\n- 2 Schlafzimmer\n- Kinderzimmer\n- Balkon Ost 14 m²\n- Kellerabteil\n- Waschküche im Haus',
      preis: 2100,
      zimmer: 4,
      flaeche: 98,
      strasse: 'Aarbergergasse 30',
      plz: '2502',
      ort: 'Biel',
      kanton: 'BE',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80'],
    },
    {
      titel: 'Praxis- oder Bürofläche im Ärztehaus',
      beschreibung: 'Gut eingerichtete Praxisfläche im etablierten Ärztehaus Luzern-Zentrum. Ideale Infrastruktur für Ärzte, Therapeuten oder andere Gesundheitsberufe. Wartezimmer, Behandlungsräume und Büro bereits vorhanden.\n\nEigenschaften:\n- 3 Behandlungszimmer\n- Empfangsbereich\n- Wartezimmer\n- Barrierefreier Zugang\n- Lift\n- Parkplätze im Haus',
      preis: 3900,
      zimmer: 4,
      flaeche: 110,
      strasse: 'Hirschmattstrasse 12',
      plz: '6003',
      ort: 'Luzern',
      kanton: 'LU',
      typ: 'gewerbe',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80'],
    },
    {
      titel: 'Grosszügiges Bauernhaus mit Riegelwerk',
      beschreibung: 'Historisches Riegelbauernhaus mit original erhaltenem Fachwerk aus dem 18. Jahrhundert. Sorgfältig renoviert, moderne Haustechnik, dennoch viel Originalsubstanz. Einzigartiger Landsitz im Seetal.\n\nHighlights:\n- 7 Zimmer\n- Scheune ausbaubar\n- Umschwung 1200 m²\n- Neue Haustechnik (Wärmepumpe, Photovoltaik)\n- Denkmalgeschützt (Fördergelder möglich)',
      preis: 1850000,
      zimmer: 7,
      flaeche: 280,
      strasse: 'Dorfstrasse 2',
      plz: '5712',
      ort: 'Beinwil am See',
      kanton: 'AG',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80'],
    },
    {
      titel: 'Neubau-Studio mit Einbauküche, Erstbezug',
      beschreibung: 'Frisch fertiggestelltes Studio im neuen Stadtentwicklungsquartier Zürich-West. Erstbezug, alles nagelneu. Hochwertige Ausstattung, smarte Raumaufteilung.\n\nDetails:\n- Einbauküche mit Backofen und Induktionskochfeld\n- Bodenheizung\n- Walk-in-Dusche\n- Einbauschrank\n- Gemeinschaftsdachterrasse\n- Fahrradstellplätze',
      preis: 1550,
      zimmer: 1,
      flaeche: 35,
      strasse: 'Turbinenstrasse 8',
      plz: '8005',
      ort: 'Zürich',
      kanton: 'ZH',
      typ: 'studio',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800&q=80'],
    },
    {
      titel: 'Grosse Lagerhalle mit Bürotrakt',
      beschreibung: 'Moderne Logistikimmobilie am Stadtrand von Olten, gut erreichbar von der A1. Hohe Hallenhöhe, grosses Rolltor und befestigte Aussenlagerfläche. Bürotrakt im Obergeschoss.\n\nEigenschaften:\n- Hallenfläche 400 m², Höhe 7 m\n- Bürofläche 80 m²\n- 2 Rolltore (4×4 m)\n- Aussenlagerfläche 200 m²\n- 10 Parkplätze\n- Starkstromanschluss 400V',
      preis: 6500,
      zimmer: 2,
      flaeche: 480,
      strasse: 'Industriestrasse 55',
      plz: '4600',
      ort: 'Olten',
      kanton: 'SO',
      typ: 'gewerbe',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&q=80'],
    },
    {
      titel: '3.5-Zimmer-Wohnung mit grossem Balkon',
      beschreibung: 'Gut unterhaltene Wohnung mit sonnigem Westbalkon und freiem Blick ins Grüne. Ruhige Quartierslage, ideale Erschliessung durch ÖV und Autobahnanschluss.\n\nDetails:\n- Wohnzimmer 28 m²\n- 2 Schlafzimmer\n- Balkon 12 m² (West)\n- Küche mit Essplatz\n- Waschmaschinenanschluss in Wohnung\n- Kellerabteil\n- Parkplatz zumietbar',
      preis: 1750,
      zimmer: 3.5,
      flaeche: 80,
      strasse: 'Rheinstrasse 72',
      plz: '4310',
      ort: 'Rheinfelden',
      kanton: 'AG',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1565183928294-7063f23ce0f8?w=800&q=80'],
    },
    {
      titel: 'Wunderschöne Villa am Genfersee',
      beschreibung: 'Exquisite Villa in privilegierter Seelage mit privatem Bootssteg. Exklusive Ausstattung, weitläufiger Parkgarten und atemberaubender Ausblick auf Lac Léman und die Alpen. Ein Angebot der Extraklasse.\n\nHighlights:\n- 8 Zimmer auf 3 Etagen\n- Privater Bootssteg\n- Parkgarten 1500 m²\n- Beheizter Aussenpool\n- Doppelgarage\n- Gästeapartment separat\n- Smart-Home-System Loxone',
      preis: 8900000,
      zimmer: 8,
      flaeche: 450,
      strasse: 'Route du Lac 5',
      plz: '1815',
      ort: 'Clarens',
      kanton: 'VD',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80'],
    },
    {
      titel: 'Sonnige Dachwohnung mit Weitsicht',
      beschreibung: 'Traumhafte Dachwohnung im Dachgeschoss eines gepflegten Altbaus. Einzigartiger Panoramablick über die Dächer von Schaffhausen und den Rhein. Grosse Dachflächenfenster für viel natürliches Licht.\n\nAusstattung:\n- Wohnfläche über zwei Ebenen\n- 3 Schlafzimmer\n- Offene Wohnküche\n- Dachterrasse 25 m²\n- Badezimmer mit freistehender Badewanne\n- Estrich mit Ausbaumöglichkeit',
      preis: 2380,
      zimmer: 3.5,
      flaeche: 100,
      strasse: 'Vordergasse 19',
      plz: '8200',
      ort: 'Schaffhausen',
      kanton: 'SH',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80'],
    },
    {
      titel: 'Engadiner Chalet mit Bergpanorama',
      beschreibung: 'Authentisches Engadiner Chalet im historischen Ortskern von Zuoz. Traditionelle Sgraffito-Fassade, vollständig renoviert und mit moderner Haustechnik ausgestattet. Atemberaubender Blick auf die Albulaalpen.\n\nHighlights:\n- 5 Zimmer auf zwei Etagen\n- Original Engadiner Gewölbekeller\n- Offener Cheminée\n- Sonnige Südterrasse 30 m²\n- Garage\n- Skigebiet Zuoz/Lagalb in 10 Minuten erreichbar',
      preis: 2200000,
      zimmer: 5,
      flaeche: 180,
      strasse: 'Via Maistra 14',
      plz: '7524',
      ort: 'Zuoz',
      kanton: 'GR',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80'],
    },
    {
      titel: 'Elegante 3.5-Zimmer-Ferienwohnung in Zuoz',
      beschreibung: 'Stilvoll eingerichtete Ferienwohnung in einem sanierten Engadiner Patrizierhaus. Ruhige Dorflage, fussläufig zu Restaurants und Einkauf. Ideale Ausgangslage für Sommer- und Winterferien.\n\nAusstattung:\n- Wohnzimmer mit Cheminée\n- Vollausgestattete Küche\n- 2 Schlafzimmer\n- Badezimmer mit Badewanne\n- Skiraum im Haus\n- Aussenstellplatz',
      preis: 1450000,
      zimmer: 3.5,
      flaeche: 105,
      strasse: 'Chastè 6',
      plz: '7524',
      ort: 'Zuoz',
      kanton: 'GR',
      typ: 'wohnung',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80'],
    },
    {
      titel: 'Gemütliche 2-Zimmer-Wohnung zur Miete',
      beschreibung: 'Helle Wohnung im ersten Obergeschoss eines gepflegten Wohnhauses in Zuoz. Ideal als Jahres- oder Ferienmietobjekt. Ruhige Lage am Dorfrand mit freiem Blick auf Wiesen und Berge.\n\nDetails:\n- Wohnzimmer mit Balkon (Südwest)\n- Schlafzimmer\n- Küche mit Essplatz\n- Badezimmer\n- Kellerabteil\n- Gemeinschaftswaschküche',
      preis: 1800,
      zimmer: 2,
      flaeche: 60,
      strasse: "Via da l'Ova 3",
      plz: '7524',
      ort: 'Zuoz',
      kanton: 'GR',
      typ: 'wohnung',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80'],
    },
    {
      titel: 'Herrschaftliches Engadiner Haus – Seltenheit',
      beschreibung: 'Imposantes Engadiner Wohnhaus aus dem 17. Jahrhundert mit original erhaltenen Gewölben, Malereien und Stuckaturen. Ein einmaliges Kulturdenkmal mit grosszügigem Umschwung mitten im Bergdorf Zuoz.\n\nHighlights:\n- 8 Zimmer\n- Denkmalgeschütztes Hauptgebäude\n- Scheune / Nebengebäude\n- Garten und Umschwung 800 m²\n- Fernblick auf Inn-Tal\n- Restaurierungskonzept vorhanden',
      preis: 3800000,
      zimmer: 8,
      flaeche: 350,
      strasse: 'Plaz 1',
      plz: '7524',
      ort: 'Zuoz',
      kanton: 'GR',
      typ: 'haus',
      modus: 'kaufen',
      bilder: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80'],
    },
    {
      titel: 'Modernes Studio im Bergdorf Zuoz',
      beschreibung: 'Neu renoviertes Studio in einer ruhigen Seitenstrasse von Zuoz. Zeitgemässe Ausstattung, warme Holztöne und grosses Panoramafenster mit Blick in die Engadiner Bergwelt. Perfekt für Paare oder als Basislager für Aktivurlauber.\n\nDetails:\n- Offene Küche mit Induktionskochfeld\n- Duschbad mit Naturstein\n- Einbauschrank\n- Holzboden durchgehend\n- Skiraum im Haus\n- E-Bike-Ladestation',
      preis: 1100,
      zimmer: 1,
      flaeche: 38,
      strasse: 'Via Salastrains 9',
      plz: '7524',
      ort: 'Zuoz',
      kanton: 'GR',
      typ: 'studio',
      modus: 'mieten',
      bilder: ['https://images.unsplash.com/photo-1501183638710-841dd1904471?w=800&q=80'],
    },
  ]

  // Fallback coordinates for addresses Nominatim can't resolve
  const fallbackCoords: Record<string, { lat: number; lng: number }> = {
    'Seepromenade 22':  { lat: 47.0489, lng: 8.3207 },
    'Im Gässli 3':      { lat: 47.3221, lng: 8.7983 },
    'Obstgartenweg 4':  { lat: 47.3153, lng: 8.5793 },
    'Markgässlein 5':   { lat: 47.5560, lng: 7.5870 },
    'Lindenstrasse 34a':{ lat: 46.7560, lng: 7.6279 },
    'Aarbergergasse 30':{ lat: 47.1368, lng: 7.2467 },
    'Dorfstrasse 2':    { lat: 47.2575, lng: 8.2016 },
    'Route du Lac 5':   { lat: 46.4494, lng: 6.9278 },
    "Via da l'Ova 3":   { lat: 46.6040, lng: 9.9610 },
    'Via Salastrains 9':{ lat: 46.6028, lng: 9.9590 },
  }

  for (const data of inserate) {
    const coords = await geocode(data.strasse, data.plz, data.ort) ?? fallbackCoords[data.strasse]
    await prisma.inserat.create({ data: { ...data, ...coords, userId: demo.id } })
    await sleep(1100)
  }

  console.log(`✓ ${inserate.length} Inserate erstellt`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
